# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    # Facebook And Twitter User Provider Service
        social:
            id: tom_sawyer.bacon_finder.security.user_provider

    firewalls:
        # disables authentication for assets and the profiler
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous: ~
            oauth:
                resource_owners:
                    facebook: "/login/check-facebook"
                    twitter: "/login/check-twitter"
                login_path: /login
                use_forward: false
                failure_path: /
                default_target_path: /account
                oauth_user_provider:
                    service: tom_sawyer.bacon_finder.security.user_provider
            logout:
                path: /logout
                target: /
        login:
            pattern: ^/login/
            security: false
            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }